### ISSUE TITLE
If instance doesn't support sharing, the link is broken

### ISSUE THREAD

**Issue by billturner** [stefanbohacek/fediverse-share-button#2]
I tried the (very neat!) widget on the documentation site but ran into a problem. It tells me that the instance I'm on (https://dice.camp) doesn't support sharing, which is fine. However, the link provided does not work.

[Line 76](https://github.com/stefanbohacek/fediverse-share-button/blob/main/fediverse-share-button/script.js#L76) of `script.js` has the slashes in the wrong direction:

```
supportNoteLink.href = `https:\\${domainInput.value}`;
```

So, in the rendered link, that becomes `https:\domain.name/username`, which when you click on it is interpreted as `https://stefanbohacek.com/domain.name/username`.

Also, as a side note, when I first tried it by entering just the base instance URL (dice.camp), there was no response. No UI change to let me know it was working in the background or something, so I thought maybe I needed to add my username as well. That's how I ended up in the situation above with the "does not support sharing" message. Not sure if you want to catch and strip off anything after the domain name when checking.

**Comment by stefanbohacek** [comment]
Ah, thank you so much for catching that, it's fixed now!
